baseURL = 'https://ya1orin.github.io/'
languageCode = 'zh-CN'
title = 'Ya1orin'
theme = 'hugo-theme-reimu'

defaultContentLanguage = 'zh-CN'
[languages]
[languages.en]
languageName = 'English'
weight = 1
[languages.zh-CN]
languageName = '简体中文'
weight = 1
hasCJKLanguage = true

[markup.goldmark.extensions.passthrough]
enable = true
delimiters.block = [["\\[", "\\]"], ["$$", "$$"]]
delimiters.inline = [["\\(", "\\)"], ["$", "$"]]

[markup.highlight]
guessSyntax = true
noClasses = false

[outputs]
home = ["Algolia", "HTML", "RSS"]

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[markup]
  [markup.tableOfContents]
    endLevel = 6
    ordered = false
    startLevel = 1

[pagination]
disableAliases = false
pagerSize = 5
path = "page"